/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser */

#ifndef _Included_com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser
#define _Included_com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser
#ifdef __cplusplus
extern "C" {
#endif
#undef com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser_NullPointer
#define com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser_NullPointer 0i64
/*
 * Class:     com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser
 * Method:    createNativeProcesser
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser_createNativeProcesser
  (JNIEnv *, jobject);

/*
 * Class:     com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser
 * Method:    releaseNativeProcesser
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser_releaseNativeProcesser
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser
 * Method:    grayBitmap
 * Signature: (JLandroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_cocoonshu_example_ndkimageprocesser_nativelayer_NDKProcesser_grayBitmap
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
